# Generated by Django 2.1.1 on 2018-12-13 07:54

from django.db import migrations

def crearTiposDeDato(apps, schema_editor):
	TipoDeDato_model = apps.get_model('api', 'TipoDeDato')
	TipoDeDato_model.objects.bulk_create([
		TipoDeDato_model(pk='seleccion_unica', nombre='Selección única', detalle=''),
		TipoDeDato_model(pk='seleccion_multiple', nombre='Selección múltiple', detalle=''),
		TipoDeDato_model(pk='valor_exacto', nombre='Valor exacto', detalle=''),
		TipoDeDato_model(pk='rango', nombre='Rango', detalle=''),
		TipoDeDato_model(pk='texto', nombre='Texto', detalle=''),
		TipoDeDato_model(pk='tabla_ram', nombre='Tabla RAM', detalle=''),
		TipoDeDato_model(pk='tabla_mico', nombre='Tabla Micobacterias', detalle=''),
		TipoDeDato_model(pk='desconocido', nombre='Desconocido', detalle=''),
	])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(crearTiposDeDato),
    ]
