# Generated by Django 2.1.1 on 2018-12-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seeder_tabla_RAM'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('respuestas', models.TextField(default=None)),
                ('deleted', models.BooleanField(default=False)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Programa')),
            ],
        ),
    ]
