# Generated by Django 2.1.2 on 2019-02-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seeder_tabla_BACT'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='estado',
            field=models.CharField(default='i', max_length=1),
            preserve_default=False,
        ),
    ]
